CREATE VIEW "BALANCE_VIEW"
AS
SELECT M.ID,M.PARENT_ID,
M.AMOUNT + AB.AMOUNT + SAB.AMOUNT AS AMOUNT
FROM SUB_ACCOUNTS_BALANCE AS SAB
LEFT OUTER JOIN ACCOUNTS_BALANCE AS AB
ON AB.ID = SAB.ID
LEFT OUTER JOIN MAIN_BALANCE AS M
ON M.ID = SAB.ID