CREATE VIEW "MAIN_BALANCE" AS SELECT 
	ACCOUNTS.ID, 
	ACCOUNTS.PARENT_ID,
	coalesce(sum(ACCOUNTS_BALANCE.AMOUNT),0.0) as AMOUNT
FROM ACCOUNTS
LEFT OUTER JOIN ACCOUNTS_BALANCE
ON ACCOUNTS.ID = ACCOUNTS_BALANCE.PARENT_ID
GROUP BY ACCOUNTS.ID