CREATE VIEW "SUB_ACCOUNTS_BALANCE" AS 
SELECT 
	ACCOUNTS.ID, 
	ACCOUNTS.PARENT_ID,
	coalesce(sum(ACCOUNTS_LEDGERS.AMOUNT),0.0) as AMOUNT
FROM ACCOUNTS
LEFT OUTER JOIN ACCOUNTS_LEDGERS
ON ACCOUNTS.ID = ACCOUNTS_LEDGERS.ACCOUNT_ID
GROUP BY ACCOUNTS.ID