CREATE TRIGGER INSERT_ACCOUNT_TRIGGER
AFTER INSERT ON ACCOUNTS
BEGIN
	SELECT * FROM BALANCE_VIEW;
END;

-- CREATE TRIGGER DELETE_ACCOUNT_TRIGGER
-- AFTER DELETE ON ACCOUNTS
-- BEGIN
-- 	SELECT * FROM BALANCE_VIEW;
-- END;

-- CREATE TRIGGER UPDATE_ACCOUNT_TRIGGER
-- UPDATE OF ID,PARENT_ID ON ACCOUNTS
-- BEGIN
-- 	SELECT * FROM BALANCE_VIEW;
-- END;