-- CREATE TRIGGER INSERT_TX_TRIGGER
-- AFTER INSERT ON TRANSACTIONS
-- BEGIN
-- 	SELECT * FROM BALANCE_VIEW;
-- END;

-- CREATE TRIGGER DELETE_TX_TRIGGER
-- AFTER DELETE ON TRANSACTIONS
-- BEGIN
-- 	SELECT * FROM BALANCE_VIEW;
-- END;

CREATE TRIGGER UPDATE_TX_TRIGGER
UPDATE OF AMOUNT,DEBIT,CREDIT ON TRANSACTIONS
BEGIN
	SELECT * FROM BALANCE_VIEW;
END;