CREATE VIEW ACCOUNTS_LEDGERS( ACCOUNT_ID,TX_ID,AMOUNT)
AS
	SELECT
		TRANSACTIONS.CREDIT as ACCOUNT_ID,
		TRANSACTIONS.ID as TX_ID,
		(0.0 - TRANSACTIONS.AMOUNT) as AMOUNT
	FROM
		TRANSACTIONS		
		WHERE TRANSACTIONS.TYPE = 'EXPENSE'
	UNION ALL
	SELECT
		TRANSACTIONS.DEBIT as ACCOUNT_ID,
		TRANSACTIONS.ID as TX_ID,
		TRANSACTIONS.AMOUNT as AMOUNT
	FROM
		TRANSACTIONS
		WHERE TRANSACTIONS.TYPE = 'INCOME'
	UNION ALL
	SELECT
		TRANSACTIONS.CREDIT as ACCOUNT_ID,
		TRANSACTIONS.ID as TX_ID,
		(0.0 - TRANSACTIONS.AMOUNT) as AMOUNT
	FROM
		TRANSACTIONS		
		WHERE TRANSACTIONS.TYPE = 'MAIN'
	UNION ALL
	SELECT
		TRANSACTIONS.DEBIT as ACCOUNT_ID,
		TRANSACTIONS.ID as TX_ID,
		TRANSACTIONS.AMOUNT as AMOUNT
	FROM
		TRANSACTIONS
		WHERE TRANSACTIONS.TYPE = 'MAIN';