CREATE VIEW "ACCOUNTS_BALANCE" AS 
SELECT 
	ACCOUNTS.ID, 
	ACCOUNTS.PARENT_ID,
	coalesce(sum(SUB_ACCOUNTS_BALANCE.AMOUNT),0.0) as AMOUNT
FROM ACCOUNTS
INNER JOIN SUB_ACCOUNTS_BALANCE
ON ACCOUNTS.ID = SUB_ACCOUNTS_BALANCE.PARENT_ID
GROUP BY ACCOUNTS.ID;