-- EXPENSE ACCOUNTS
CREATE VIEW ACCOUNTS_EXPENSE AS 
    SELECT * 
    FROM ACCOUNTS 
    WHERE NUMBER > 500000 AND 
        NUMBER % 1000 = 0 AND 
        PARENT_ID IS NOT NULL
    ORDER BY NUMBER;

-- INCOME ACCOUNTS
CREATE VIEW ACCOUNTS_INCOME AS 
    SELECT * 
    FROM ACCOUNTS 
    WHERE NUMBER > 400000 AND 
        NUMBER < 500000 AND 
        NUMBER % 1000 = 0 
    ORDER BY NUMBER;

-- MAIN ACCOUNTS
CREATE VIEW ACCOUNTS_MAIN AS
    SELECT * 
    FROM ACCOUNTS 
    WHERE PARENT_ID IN (
        SELECT ID 
        FROM ACCOUNTS 
        WHERE NUMBER = 100000 OR
            NUMBER = 200000 OR 
            NUMBER = 300000);