CREATE TABLE "ACCOUNTS" (
	"ID"	TEXT,
	"NAME"	TEXT,
	"NUMBER"	INTEGER,
	"SIGN"	INTEGER,
	"PARENT_ID"	TEXT,
	FOREIGN KEY("PARENT_ID") REFERENCES "ACCOUNTS"("ID") ON UPDATE CASCADE,
	PRIMARY KEY("ID")
);

CREATE TABLE "CURRENCIES" (
	"KEY"	TEXT NOT NULL,
	"SYMBOL"	TEXT NOT NULL,
	"NAME"	TEXT,
	PRIMARY KEY("KEY")
);

CREATE TABLE "TRANSACTIONS" (
	"ID"	TEXT NOT NULL,
	"DATE"	TEXT NOT NULL,
	"DESCRIPTION"	TEXT NOT NULL,
	"DEBIT"	TEXT NOT NULL,
	"CREDIT"	TEXT NOT NULL,
	"TYPE"	TEXT NOT NULL,
	"AMOUNT_LOC"	NUMERIC(20, 2) NOT NULL CHECK("AMOUNT_LOC" > 0.0),
	"CURR_LOC"	TEXT NOT NULL,
	"AMOUNT"	NUMERIC(20, 2) NOT NULL CHECK("AMOUNT" > 0.0),
	"NOTES"	TEXT NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("DEBIT") REFERENCES "ACCOUNTS"("ID") ON DELETE RESTRICT,
	FOREIGN KEY("CREDIT") REFERENCES "ACCOUNTS"("ID") ON DELETE RESTRICT
	FOREIGN KEY("CURR_LOC") REFERENCES "CURRENCIES"("SYMBOL") ON DELETE RESTRICT
);