CREATE VIEW "TRANSACTIONS_VIEW" AS
SELECT
	T.ID, 
	T.DATE, 
	T.DESCRIPTION,
	T.DEBIT AS DEBIT_ID, 
	AD.NAME AS DEBIT_NAME,
	(1 * AD.SIGN) AS DEBIT_DIR,
	AD.PARENT_ID AS DEBIT_PARENT,
	T.CREDIT AS CREDIT_ID, 
	AC.NAME AS CREDIT_NAME,
	(-1 * AC.SIGN) AS CREDIT_DIR,
	AC.PARENT_ID AS CREDIT_PARENT,
	T.TYPE,
	C.SYMBOL,
	T.AMOUNT_LOC ,
	T.AMOUNT,
	T.NOTES
FROM TRANSACTIONS AS T
LEFT OUTER JOIN ACCOUNTS AS AD
LEFT OUTER JOIN ACCOUNTS AS AC
LEFT OUTER JOIN CURRENCIES as C
WHERE AD.ID = T.DEBIT AND
	  AC.ID = T.CREDIT AND
	  C.KEY = T.CURR_LOC