-- EXPENSE SUB-ACCOUNTS
CREATE VIEW SUB_ACCOUNTS_EXPENSE AS 
    SELECT * 
    FROM ACCOUNTS 
    WHERE PARENT_ID IN (
        SELECT ID 
        FROM ACCOUNTS_EXPENSE);

-- INCOME SUB-ACCOUNTS
CREATE VIEW SUB_ACCOUNTS_INCOME AS 
    SELECT * 
    FROM ACCOUNTS 
    WHERE PARENT_ID IN (
        SELECT ID 
        FROM ACCOUNTS_INCOME);

-- MAIN SUB-ACCOUNTS
CREATE VIEW SUB_ACCOUNTS_MAIN AS 
    SELECT * 
    FROM ACCOUNTS 
    WHERE PARENT_ID IN (
        SELECT ID 
        FROM ACCOUNTS_MAIN);