CREATE VIEW BALANCE_VIEW
AS
select AB.ID, A.NAME, A.NUMBER AS NUMBER, AB.PARENT_ID, P.NAME AS PARENT_NAME, AB.AMOUNT  from 
(
SELECT * FROM ACCOUNTS_BALANCE 
UNION ALL
SELECT * FROM SUB_ACCOUNTS_BALANCE
) as AB
left outer join ACCOUNTS as A
on A.ID = AB.ID
LEFT OUTER JOIN ACCOUNTS AS P
ON P.ID = AB.PARENT_ID
order by NUMBER;