-- EXPENSE LEDGER
CREATE VIEW SUB_EXPENSE_LEDGERS AS
    SELECT DATE,
            DEBIT_ID AS ACCOUNT_ID,
            DEBIT_NAME AS ACCOUNT_NAME,
            DEBIT_PARENT AS ACCOUNT_PARENT, 
            SYMBOL,
            AMOUNT 
    FROM TRANSACTIONS_VIEW 
    WHERE TYPE='EXPENSE' AND
            DEBIT_PARENT IS NOT NULL;

-- INCOME LEDGER
CREATE VIEW SUB_INCOME_LEDGERS AS
    SELECT DATE,
            CREDIT_ID AS ACCOUNT_ID,
            CREDIT_NAME AS ACCOUNT_NAME,
            CREDIT_PARENT AS ACCOUNT_PARENT, 
            SYMBOL,
            AMOUNT 
    FROM TRANSACTIONS_VIEW 
    WHERE TYPE='INCOME' AND
            CREDIT_PARENT IS NOT NULL;