INSERT INTO CURRENCIES (KEY,SYMBOL,NAME) VALUES
('INR','₹','Indian Rupee'),
('ALL','Lek','Albanian Lek'),
('AFN','؋','Afghan Afghani'),
('ARS','$','Argentine Peso'),
('AWG','ƒ','Aruban Guilder'),
('AUD','$','Australian Dollar'),
('AZN','₼','Azerbaijani Manat'),
('BSD','$','Bahamian Dollar'),
('BBD','$','Barbadian Dollar'),
('BYN','Br','Belarusian Ruble'),
('BZD','BZ$','Belize Dollar'),
('BMD','$','Bermudan Dollar'),
('BOB','$b','Bolivian Boliviano'),
('BAM','KM','Bosnia-Herzegovina Convertible Mark'),
('BWP','P','Botswana Pula'),
('BGN','Лв','Bulgarian Lev'),
('BRL','R$','Brazilian Real'),
('BND','$','Brunei Dollar'),
('KHR','៛','Cambodian riel'),
('CAD','$','Canadian Dollar'),
('KYD','$','Cayman Islands Dollar'),
('CLP','$','Chilean Peso'),
('CNY','¥','Chinese Yuan'),
('COP','$','Colombian Peso'),
('CRC','₡','Costa Rican Colon'),
('HRK','kn','Croatian Kuna'),
('CUP','$','Cuban Peso'),
('CZK','Kc','Czech Koruna'),
('DKK','kr','Danish Krone'),
('DOP','RD$','Dominican Peso'),
('XCD','$','East Caribbean Dollar'),
('EGP','£','Egyptian Pound'),
('SVC','$','Salvadoran Colon'),
('EUR','€','Euro'),
('FKP','£','Falkland Islands Pound'),
('FJD','$','Fijian Dollar'),
('GHS','¢','Ghanaian Cedi'),
('GIP','£','Gibraltar Pound'),
('GTQ','Q','Guatemalan Quetzal'),
('GGP','£','Guernsey Pound'),
('GYD','$','Guyana Dollar'),
('HNL','L','Honduran Lempira'),
('HKD','$','Hong Kong Dollar'),
('HUF','Ft','Hungarian Forint'),
('ISK','kr','Icelandic Krona'),
('IDR','Rp','Indonesian Rupiah'),
('IRR','﷼','Iranian Rial'),
('IMP','£','Manx pound'),
('ILS','₪','Israeli New Shekel'),
('JMD','J$','Jamaican Dollar'),
('JPY','¥','Japanese Yen'),
('JEP','£','Jersey pound'),
('KZT','₸','Kazakhstani Tenge'),
('KPW','₩','North Korean Won'),
('KRW','₩','South Korean won'),
('KGS','Лв','Kyrgystani Som'),
('LAK','₭','Laotian Kip'),
('LBP','£','Lebanese pound'),
('LRD','$','Liberian Dollar'),
('MKD','Ден','Macedonian Denar'),
('MYR','RM','Malaysian Ringgit'),
('MZN','MT','Mozambican metical'),
('NAD','$','Namibian Dollar'),
('NPR','Rs','Nepalese Rupee'),
('ANG','ƒ','Netherlands Antillean Guilder'),
('NZD','$','New Zealand Dollar'),
('NIO','C$','Nicaraguan Cordoba'),
('NGN','₦','Nigerian Naira'),
('NOK','kr','Norwegian Krone'),
('OMR','ر.ع.','Omani Rial'),
('PKR','Rs','Pakistani Rupee'),
('PAB','B/.','Panamanian Balboa'),
('PYG','Gs','Paraguayan Guarani'),
('PEN','S/.','Sol'),
('PHP','₱','Philippine peso'),
('PLN','zł','Polish Zloty'),
('QAR','ر.ق','Qatari Riyal'),
('RON','lei','Romanian Leu'),
('RUB','₽','Russian Ruble'),
('SHP','£','St. Helena Pound'),
('SAR','﷼','Saudi Riyal'),
('RSD','din','Serbian Dinar'),
('SCR','SRe','Seychellois Rupee'),
('SGD','$','Singapore Dollar'),
('SBD','$','Solomon Islands Dollar'),
('SOS','S','Somali Shilling'),
('ZAR','R','South African Rand'),
('LKR','Rs','Sri Lankan Rupee'),
('SEK','kr','Swedish Krona'),
('CHF','CHF','Swiss Franc'),
('SRD','$','Surinamese Dollar'),
('SYP','£','Syrian Pound'),
('TWD','NT$','New Taiwan dollar'),
('THB','฿','Thai Baht'),
('TTD','TT$','Trinidad and Tobago Dollar'),
('MUR','Rs','Mauritian Rupee'),
('MXN','$','Mexican Peso'),
('MNT','₮','Mongolian Tugrik'),
('TRY','฿','Turkish lira'),
('TVD','$','Tuvaluan dollar'),
('UAH','₴','Ukrainian hryvnia'),
('AED','د.إ','United Arab Emirates Dirham'),
('GBP','£','United Kingdom Pound'),
('USD','$','United States Dollar'),
('UYU','$U','Uruguayan Peso'),
('UZS','som','Uzbekistani Som'),
('VEF','Bs','Venezuelan bolovar'),
('VND','₫','Vietnamese dong'),
('YER','﷼','Yemeni Rial'),
('ZWD','Z$','Zimbabwean dollar')