CREATE TABLE "TRANSACTIONS" (
	"ID"	TEXT NOT NULL,
	"DATE"	TEXT NOT NULL,
	"DESCRIPTION"	INTEGER NOT NULL,
	"DEBIT"	TEXT NOT NULL,
	"CREDIT"	TEXT NOT NULL,
	"TYPE"	TEXT NOT NULL,
	"AMOUNT_LOC"	NUMERIC(20,2) NOT NULL CHECK ("AMOUNT">0.0),
	"CURR_LOC"	TEXT NOT NULL,
	"AMOUNT"	INTEGER NOT NULL,
	FOREIGN KEY("DEBIT") REFERENCES "ACCOUNTS"("ID") ON DELETE RESTRICT,
	FOREIGN KEY("CREDIT") REFERENCES "ACCOUNTS"("ID") ON DELETE RESTRICT,
	PRIMARY KEY("ID")
);