SELECT 
T.ID,T.DATE,T.DESCRIPTION,
T.DEBIT_ID, T.DEBIT_NAME, T.DEBIT_DIR, AD.NAME AS DEBIT_PARENT,  
T.CREDIT_ID, T.CREDIT_NAME, T.CREDIT_DIR, AC.NAME AS CREDIT_PARENT,  
T.TYPE,
T.SYMBOL,
T.AMOUNT_LOC
FROM TRANSACTIONS_VIEW AS T
LEFT OUTER JOIN ACCOUNTS AS AD
ON AD.ID = T.DEBIT_PARENT
LEFT OUTER JOIN ACCOUNTS AS AC
ON AC.ID = T.CREDIT_PARENT