select  TRANSACTIONS.ID,TRANSACTIONS.DATE,TRANSACTIONS.DESCRIPTION,D.NAME as DEBIT ,C.NAME as CREDIT,TRANSACTIONS.TYPE,TRANSACTIONS.AMOUNT 
FROM TRANSACTIONS 
LEFT OUTER JOIN ACCOUNTS AS D
ON D.ID = TRANSACTIONS.DEBIT
LEFT OUTER JOIN ACCOUNTS AS C
ON C.ID = TRANSACTIONS.CREDIT
where TRANSACTIONS.DATE BETWEEN '2022-04-01' AND '2022-04-31'
order by TRANSACTIONS.TYPE